/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

import javax.swing.JOptionPane;

/**
 *
 * @author 솔데스크
 */
public class Frame_Register extends javax.swing.JFrame {
    /**
     * Creates new form Frame_Register
     */
    public Frame_Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Radio_Male = new javax.swing.JRadioButton();
        Radio_Female = new javax.swing.JRadioButton();
        Register_Id = new javax.swing.JTextField();
        Regsiter_Phone = new javax.swing.JTextField();
        Register_Password = new javax.swing.JPasswordField();
        Register_Btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Register_Check = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("아이디:");

        jLabel2.setText("비밀번호:");

        jLabel3.setText("전화번호:");

        jLabel4.setText("성별:");

        Radio_Male.setText("남자");

        Radio_Female.setText("여자");

        Register_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_IdActionPerformed(evt);
            }
        });

        Register_Btn.setText("회원가입");
        Register_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_BtnActionPerformed(evt);
            }
        });

        jLabel5.setText("회원가입창");

        Register_Check.setText("중복확인");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(71, 71, 71)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel1))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(Register_Id)
                                                                        .addComponent(Regsiter_Phone)
                                                                        .addComponent(Register_Password,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                150,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(Register_Check))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(Radio_Male)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(Radio_Female))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(162, 162, 162)
                                                .addComponent(Register_Btn))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(jLabel5)))
                                .addContainerGap(14, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel5)
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(Register_Id, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Register_Check))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(Register_Password, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(Regsiter_Phone, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(Radio_Male)
                                        .addComponent(Radio_Female))
                                .addGap(27, 27, 27)
                                .addComponent(Register_Btn)
                                .addContainerGap(29, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>

    private void Register_IdActionPerformed(java.awt.event.ActionEvent evt) {


    }

    private void Register_BtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Register_BtnActionPerformed
        // TODO add your handling code here:

        // 1. 입력값 꺼내기
        String id = Register_Id.getText();
        String pw = new String(Register_Password.getPassword());
        String phone = Regsiter_Phone.getText();
        String gender = Radio_Male.isSelected() ? "M" : "F";
        DB_Connect Vaild = new DB_Connect();

        System.out.println(id + " " + pw + " " + phone + " " + gender);

        // 1.5. 비밀번호 유효성 검사
        if (!Vaild.isValidPassword(pw)) {
            JOptionPane.showMessageDialog(this, "비밀번호는 8자 이상, 영문자/숫자/특수문자를 포함해야 합니다.");
            return; // 실패 시 아래로 안 내려가고 함수 종료
        }
        // 1.5. 전화번호 유효성 검사
        if (phone.equals("")) {
            JOptionPane.showMessageDialog(this, "전번입력해주세요.");
            return; // 실패 시 아래로 안 내려가고 함수 종료
        }
        // 1.5. 성별 유효성 검사
        if (!Vaild.isValidPassword(gender)) {
            JOptionPane.showMessageDialog(this, "비밀번호는 8자 이상, 영문자/숫자/특수문자를 포함해야 합니다.");
            return; // 실패 시 아래로 안 내려가고 함수 종료
        }

        try {
            // phone="";
            throw new Exception();
        } catch (Exception e) {

        }

        // 2. DB 연결 및 INSERT 실행
        try {
            // 오라클 드라이버 로드
            Class.forName("oracle.jdbc.driver.OracleDriver");

            // DB 연결
            Connection conn = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:xe", "admin", "12345");

            // SQL 준비
            String sql = "INSERT INTO MEMBERS (member_id, password, phone, gender) VALUES (?, ?, ?, ?)";
            PreparedStatement pstmt = conn.prepareStatement(sql);

            // ? 에 값 넣기
            pstmt.setString(1, id);
            pstmt.setString(2, pw);
            pstmt.setString(3, phone);
            pstmt.setString(4, gender);

            // SQL 실행
            try {

                int result = pstmt.executeUpdate();

                // 결과 확인
                if (result > 0) {
                    JOptionPane.showMessageDialog(this, "회원가입 성공!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "회원가입 실패...");

            }

            // 자원 정리
            pstmt.close();
            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "DB 오류: " + e.getMessage());
        }

    }// GEN-LAST:event_Register_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Register.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Register.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Register.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Register.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JRadioButton Radio_Female;
    private javax.swing.JRadioButton Radio_Male;
    private javax.swing.JButton Register_Btn;
    private javax.swing.JButton Register_Check;
    private javax.swing.JTextField Register_Id;
    private javax.swing.JPasswordField Register_Password;
    private javax.swing.JTextField Regsiter_Phone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration
}
