/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 솔데스크
 */


public class Frame_Cart extends javax.swing.JFrame {
    // 장바구니 데이터 로딩 (DB → JTable)
    public void loadCartDataFromDatabase() {
    DefaultTableModel model = (DefaultTableModel) Tbl_Cart.getModel();
    model.setRowCount(0); // 기존 데이터 삭제

    try (Connection conn = DriverManager.getConnection(
         "jdbc:oracle:thin:@localhost:1521:xe", "member", "12345")) {

        String sql = "SELECT name, spec, price, description FROM cart";
        PreparedStatement pstmt = conn.prepareStatement(sql);
        ResultSet rs = pstmt.executeQuery();

        while (rs.next()) {
            String name = rs.getString("name");
            String spec = rs.getString("spec");
            String price = rs.getString("price");
            String description = rs.getString("description");
            model.addRow(new Object[]{name, spec, price, description});
        }

        rs.close();
        pstmt.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
}

// 장바구니 데이터 저장 (JTable → DB)
public void saveCartDataToDatabase() {
    try (Connection conn = DriverManager.getConnection(
         "jdbc:oracle:thin:@localhost:1521:xe", "member", "12345")) {

        String deleteSql = "DELETE FROM cart";
        PreparedStatement deleteStmt = conn.prepareStatement(deleteSql);
        deleteStmt.executeUpdate();
        deleteStmt.close();

        String insertSql = "INSERT INTO cart (name, spec, price, description) VALUES (?, ?, ?, ?)";
        PreparedStatement pstmt = conn.prepareStatement(insertSql);

        DefaultTableModel model = (DefaultTableModel) Tbl_Cart.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            pstmt.setString(1, model.getValueAt(i, 0).toString());
            pstmt.setString(2, model.getValueAt(i, 1).toString());
            pstmt.setString(3, model.getValueAt(i, 2).toString());
            pstmt.setString(4, model.getValueAt(i, 3).toString());
            pstmt.addBatch();
        }

        pstmt.executeBatch();
        pstmt.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    public void loadCpuListToCart(List<CPU_DB> cpulList) {
    DefaultTableModel model = (DefaultTableModel) Tbl_Cart.getModel();
    model.setRowCount(0); // 기존 데이터 초기화

    for (CPU_DB cpu : cpulList) {
        model.addRow(new Object[]{
            cpu.getcpuid(),        // 제품 명
            cpu.getcpudata(),      // 성능
            cpu.getcpuprice(),     // 가격
            cpu.getcpuprodctid()   // 제품 정보
        });
    }
}
    public static Frame_Cart instance;
    /**
     * Creates new form NewJFrame
     */
    public Frame_Cart() {
          instance = this;
            initComponents();

       loadCartDataFromDatabase(); // 장바구니 열릴 때 DB 불러오기

        addWindowListener(new WindowAdapter() {
        @Override
        public void windowClosing(WindowEvent e) {
            saveCartDataToDatabase(); // 창 닫을 때 DB 저장
        }
    });
    
    }
    public void addRowToCart(String name, String spec, String price, String desc) {
        DefaultTableModel model = (DefaultTableModel) Tbl_Cart.getModel();
     model.insertRow(0, new Object[]{name, spec, price, desc}); // 맨 위에 삽입
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Cart = new javax.swing.JTable();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 480));

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        jLabel1.setText("장바구니");

        jButton1.setText("구매하기");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Tbl_Cart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
              
            },
            new String [] {
                "제품 명", "성능", "가격", "설명"
            }
        ));
        jScrollPane1.setViewportView(Tbl_Cart);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Cart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTable Tbl_Cart;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}
