/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/*
    아이템 보여주고 1번째는 아이템 번호, 2번째는 아이템 이름 
*/

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.util.ArrayList;

import javax.swing.ImageIcon;

/**
 *
 * @author 솔데스크
 */
public class Frame_Gpu extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Cpu
     */
    public Frame_Gpu() {
    	
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Lbl_Gpu1 = new javax.swing.JLabel();
        Lbl_Gpu2 = new javax.swing.JLabel();
        Lbl_Gpu3 = new javax.swing.JLabel();
        Lbl_Name1 = new javax.swing.JLabel();
        Lbl_Name2 = new javax.swing.JLabel();
        Lbl_Name3 = new javax.swing.JLabel();
        Lbl_Price1 = new javax.swing.JLabel();
        Lbl_Price2 = new javax.swing.JLabel();
        Lbl_Price3 = new javax.swing.JLabel();
        Lbl_Info2 = new javax.swing.JLabel();
        Lbl_Info3 = new javax.swing.JLabel();
        Lbl_Info1 = new javax.swing.JLabel();
        Lbl_Exam1 = new javax.swing.JLabel();
        Lbl_Exam3 = new javax.swing.JLabel();
        Lbl_Exam2 = new javax.swing.JLabel();
        Button_Next = new javax.swing.JButton();
        Btn_Selec1 = new javax.swing.JButton();
        Btn_Selec2 = new javax.swing.JButton();
        Btn_Selec3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Btn_MoveSelect = new javax.swing.JButton();

        ArrayList<Disk_02> diskList = Disk_02.getDiskList();
        Disk_02 disk = diskList.get(0);
        Object[][] data = new Object[diskList.size()][11];

        for (int i = 0; i < diskList.size(); i++) {
        	Disk_02 ds = diskList.get(i);
            data[i][0] = ds.getProdctid();
            data[i][1] = ds.getDiskid();
            data[i][2] = ds.getDiskdata();
            data[i][3] = ds.getPrice();
        }


        jLabel7.setText("이름:");

        jLabel9.setText("이름:");

        jLabel15.setText("정보:");

        jLabel17.setText("정보:");

        jLabel20.setText("설명:");

        jButton2.setText("jButton1");

        jLabel6.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(430, 480));

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel1.setText("GPU");

        jLabel2.setFont(new java.awt.Font("맑은 고딕", 3, 18)); // NOI18N
        jLabel2.setText("아이템 추가는 소스에서 추가 가능");

        ImageIcon icon = new ImageIcon("C:\\test1234\\Git_onboarding\\Fix_Error\\src\\NVIDIA RTX 5090.jpg");
        Image Image = icon.getImage();
        Image resizeImage = Image.getScaledInstance( 100, 80, Image.SCALE_SMOOTH);
        ImageIcon resizedIcon = new ImageIcon(resizeImage);
        Lbl_Gpu1.setIcon(resizedIcon);
        Lbl_Gpu1.setText("");

        ImageIcon icon1 = new ImageIcon("C:\\test1234\\Git_onboarding\\Fix_Error\\src\\NVIDIA RTX 5080.jpg");
        Image Image1 = icon1.getImage();
        Image resizeImage1 = Image1.getScaledInstance( 100, 80, Image.SCALE_SMOOTH);
        ImageIcon resizedIcon1 = new ImageIcon(resizeImage1);
        Lbl_Gpu2.setIcon(resizedIcon1);
        Lbl_Gpu2.setText("");

        ImageIcon icon2 = new ImageIcon("C:\\test1234\\Git_onboarding\\Fix_Error\\src\\NVIDIA RTX 5070 Ti.png");
        Image Image2 = icon2.getImage();
        Image resizeImage2 = Image2.getScaledInstance( 100, 80, Image.SCALE_SMOOTH);
        ImageIcon resizedIcon2 = new ImageIcon(resizeImage2);
        Lbl_Gpu3.setIcon(resizedIcon2);
        Lbl_Gpu3.setText("");

        Lbl_Name1.setText("이름:");

        Lbl_Name2.setText("이름:");

        Lbl_Name3.setText("이름:");

        Lbl_Price1.setText("가격:");

        Lbl_Price2.setText("가격:");

        Lbl_Price3.setText("가격:");

        Lbl_Info2.setText("정보:");

        Lbl_Info3.setText("정보:");

        Lbl_Info1.setText("정보:");

        Lbl_Exam1.setText("설명:");

        Lbl_Exam3.setText("설명:");

        Lbl_Exam2.setText("설명:");

        Button_Next.setLabel("다음 페이지");
        Button_Next.setPreferredSize(new java.awt.Dimension(100, 30));
        Button_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_NextActionPerformed(evt);
            }
        });

        Btn_Selec1.setText("추가");
        Btn_Selec1.addActionListener(new java.awt.event.ActionListener() {
            @Override
           public void actionPerformed(ActionEvent e) {
               // CPU 데이터 리스트 가져오기
               ArrayList<Disk_02> diskList = Disk_02.getDiskList();

           if (diskList.size() > 6) {
        	   Disk_02 disk = diskList.get(6);; // 세번째 CPU만 선택

               String cpuid = disk.getDiskid();
               String cpudata = disk.getDiskdata();
               String cpuprice = disk.getPrice();
               String cpuprodctid = disk.getProdctid();
    
               // 세번쨰 CPU 장바구니로 이동
             if (Frame_Cart.instance == null || !Frame_Cart.instance.isDisplayable()) {
               Frame_Cart cart = new Frame_Cart();
               cart.setVisible(true);
   }

               //CPU값 장바구니에 저장
               Frame_Cart.instance.addRowToCart(cpuid, cpudata, cpuprice, cpuprodctid);
               Frame_Cart.instance.saveCartDataToDatabase();
           }
           
       }
   });

        Btn_Selec2.setText("추가");
        Btn_Selec2.addActionListener(new java.awt.event.ActionListener() {
            @Override
           public void actionPerformed(ActionEvent e) {
               // CPU 데이터 리스트 가져오기
               ArrayList<Disk_02> diskList = Disk_02.getDiskList();

           if (diskList.size() > 7) {
        	   Disk_02 disk = diskList.get(7);; // 세번째 CPU만 선택

               String cpuid = disk.getDiskid();
               String cpudata = disk.getDiskdata();
               String cpuprice = disk.getPrice();
               String cpuprodctid = disk.getProdctid();
    
               // 세번쨰 CPU 장바구니로 이동
             if (Frame_Cart.instance == null || !Frame_Cart.instance.isDisplayable()) {
               Frame_Cart cart = new Frame_Cart();
               cart.setVisible(true);
   }

               //CPU값 장바구니에 저장
               Frame_Cart.instance.addRowToCart(cpuid, cpudata, cpuprice, cpuprodctid);
               Frame_Cart.instance.saveCartDataToDatabase();
           }
           
       }
   });

        Btn_Selec3.setText("추가");
        Btn_Selec3.addActionListener(new java.awt.event.ActionListener() {
            @Override
           public void actionPerformed(ActionEvent e) {
               // CPU 데이터 리스트 가져오기
               ArrayList<Disk_02> diskList = Disk_02.getDiskList();

           if (diskList.size() > 8) {
        	   Disk_02 disk = diskList.get(8);; // 세번째 CPU만 선택

               String cpuid = disk.getDiskid();
               String cpudata = disk.getDiskdata();
               String cpuprice = disk.getPrice();
               String cpuprodctid = disk.getProdctid();
    
               // 세번쨰 CPU 장바구니로 이동
             if (Frame_Cart.instance == null || !Frame_Cart.instance.isDisplayable()) {
               Frame_Cart cart = new Frame_Cart();
               cart.setVisible(true);
   }

               //CPU값 장바구니에 저장
               Frame_Cart.instance.addRowToCart(cpuid, cpudata, cpuprice, cpuprodctid);
               Frame_Cart.instance.saveCartDataToDatabase();
           }
           
       }
   });
        
        if (diskList.size() > 6) {
        	Disk_02 disk6 = diskList.get(6);
        jLabel3.setText(disk6.getPrice());
        jLabel4.setText(disk6.getDiskid());
        jLabel5.setText(disk6.getProdctid());
        jLabel8.setText(disk6.getDiskdata());
        }
        
        if (diskList.size() > 7) {
        	Disk_02 disk7 = diskList.get(7);
        jLabel10.setText(disk7.getDiskid());
        jLabel11.setText(disk7.getPrice());
        jLabel12.setText(disk7.getProdctid());
        jLabel13.setText(disk7.getDiskdata());
        }
        
        if (diskList.size() > 8) {
        	Disk_02 disk8 = diskList.get(8);
        jLabel14.setText(disk8.getDiskid());
        jLabel16.setText(disk8.getPrice());
        jLabel18.setText(disk8.getProdctid());
        jLabel19.setText(disk8.getDiskdata());
        }
        Btn_MoveSelect.setText("초기화면");
        Btn_MoveSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_MoveSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2) // 좌측 상단 설명 텍스트
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1) // 우측 상단 "GPU"
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        // GPU 3
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Lbl_Gpu3, 100, 100, 100)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Lbl_Name3)
                                .addComponent(Lbl_Price3)
                                .addComponent(Lbl_Info3)
                                .addComponent(Lbl_Exam3)))
                        // GPU 2
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Lbl_Gpu2, 100, 100, 100)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Lbl_Name2)
                                .addComponent(Lbl_Price2)
                                .addComponent(Lbl_Info2)
                                .addComponent(Lbl_Exam2)))
                        // GPU 1
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Lbl_Gpu1, 100, 100, 100)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Lbl_Name1)
                                .addComponent(Lbl_Price1)
                                .addComponent(Lbl_Info1)
                                .addComponent(Lbl_Exam1))))
                    .addComponent(Btn_MoveSelect, 100, 100, 100))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)   // 이름
                            .addComponent(jLabel3)   // 가격
                            .addComponent(jLabel5)   // 정보
                            .addComponent(jLabel8)   // 설명
                            .addComponent(jLabel10)  // 이름
                            .addComponent(jLabel11)  // 가격
                            .addComponent(jLabel12)  // 정보
                            .addComponent(jLabel13)  // 설명
                            .addComponent(jLabel14)  // 이름
                            .addComponent(jLabel16)  // 가격
                            .addComponent(jLabel18)  // 정보
                            .addComponent(jLabel19)) // 설명
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn_Selec1)
                            .addComponent(Btn_Selec2)
                            .addComponent(Btn_Selec3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Button_Next, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    // GPU 1
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl_Gpu1, 100, 100, 100)
                        .addGap(18, 18, 18)
                        .addComponent(Lbl_Gpu2, 100, 100, 100)
                        .addGap(18, 18, 18)
                        .addComponent(Lbl_Gpu3, 100, 100, 100))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl_Name1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_Price1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_Info1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_Exam1)
                        .addGap(18, 18, 18)
                        .addComponent(Lbl_Name2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_Price2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_Info2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_Exam2)
                        .addGap(18, 18, 18)
                        .addComponent(Lbl_Name3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_Price3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_Info3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_Exam3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn_Selec1)
                        .addGap(95)
                        .addComponent(Btn_Selec2)
                        .addGap(95)
                        .addComponent(Btn_Selec3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_Next, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_MoveSelect, 30, 30, 30))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_NextActionPerformed
        Frame_GpuNext next = new Frame_GpuNext();
        dispose();
        next.setVisible(true);
    }//GEN-LAST:event_Button_NextActionPerformed

    private void Btn_Selec1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Selec1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Selec1ActionPerformed

    private void Btn_Selec2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Selec2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Selec2ActionPerformed

    private void Btn_Selec3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Selec3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Selec3ActionPerformed
    private void Btn_MoveSelectActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        Frame_Select next = new Frame_Select();
        dispose();
        next.setVisible(true);
    }                                              


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Gpu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Gpu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Gpu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Gpu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Gpu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_MoveSelect;
    private javax.swing.JButton Btn_Selec1;
    private javax.swing.JButton Btn_Selec2;
    private javax.swing.JButton Btn_Selec3;
    private javax.swing.JButton Button_Next;
    private javax.swing.JLabel Lbl_Exam1;
    private javax.swing.JLabel Lbl_Exam2;
    private javax.swing.JLabel Lbl_Exam3;
    private javax.swing.JLabel Lbl_Gpu1;
    private javax.swing.JLabel Lbl_Gpu2;
    private javax.swing.JLabel Lbl_Gpu3;
    private javax.swing.JLabel Lbl_Info1;
    private javax.swing.JLabel Lbl_Info2;
    private javax.swing.JLabel Lbl_Info3;
    private javax.swing.JLabel Lbl_Name1;
    private javax.swing.JLabel Lbl_Name2;
    private javax.swing.JLabel Lbl_Name3;
    private javax.swing.JLabel Lbl_Price1;
    private javax.swing.JLabel Lbl_Price2;
    private javax.swing.JLabel Lbl_Price3;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
