/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/*
    아이템 보여주고 1번째는 아이템 번호, 2번째는 아이템 이름 
*/

import java.util.ArrayList;

/**
 *
 * @author 솔데스크
 */
public class Frame_GpuNext2 extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Cpu
     */
    public Frame_GpuNext2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Lbl_Gpu4 = new javax.swing.JLabel();
        Lbl_Gpu5 = new javax.swing.JLabel();
        Lbl_Gpu6 = new javax.swing.JLabel();
        Lbl_Name4 = new javax.swing.JLabel();
        Lbl_Name5 = new javax.swing.JLabel();
        Lbl_Name6 = new javax.swing.JLabel();
        Lbl_Price4 = new javax.swing.JLabel();
        Lbl_Price5 = new javax.swing.JLabel();
        Lbl_Price6 = new javax.swing.JLabel();
        Lbl_Info5 = new javax.swing.JLabel();
        Lbl_Info6 = new javax.swing.JLabel();
        Lbl_Info4 = new javax.swing.JLabel();
        Lbl_Exam4 = new javax.swing.JLabel();
        Lbl_Exam6 = new javax.swing.JLabel();
        Lbl_Exam5 = new javax.swing.JLabel();
        Button_Previous = new javax.swing.JButton();
        Btn_Selec4 = new javax.swing.JButton();
        Btn_Selec5 = new javax.swing.JButton();
        Btn_Selec6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        jLabel7.setText("이름:");

        jLabel9.setText("이름:");

        jLabel15.setText("정보:");

        jLabel17.setText("정보:");

        jLabel20.setText("설명:");

        jButton2.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel1.setText("GPU");

        jLabel2.setFont(new java.awt.Font("맑은 고딕", 3, 18)); // NOI18N
        jLabel2.setText("아이템 추가는 소스에서 추가 가능");

        Lbl_Gpu4.setText("그림 넣어주세요4");

        Lbl_Gpu5.setText("그림 넣어주세요5");

        Lbl_Gpu6.setText("그림 넣어주세요6");

        Lbl_Name4.setText("이름:");

        Lbl_Name5.setText("이름:");

        Lbl_Name6.setText("이름:");

        Lbl_Price4.setText("가격:");

        Lbl_Price5.setText("가격:");

        Lbl_Price6.setText("가격:");

        Lbl_Info5.setText("정보:");

        Lbl_Info6.setText("정보:");

        Lbl_Info4.setText("정보:");

        Lbl_Exam4.setText("설명:");

        Lbl_Exam6.setText("설명:");

        Lbl_Exam5.setText("설명:");

        Button_Previous.setText("이전 페이지");
        Button_Previous.setPreferredSize(new java.awt.Dimension(100, 30));
        Button_Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_PreviousActionPerformed(evt);
            }
        });

        Btn_Selec4.setText("jButton1");
        Btn_Selec4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Selec4ActionPerformed(evt);
            }
        });

        Btn_Selec5.setText("jButton1");
        Btn_Selec5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Selec5ActionPerformed(evt);
            }
        });

        Btn_Selec6.setText("jButton1");
        Btn_Selec6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Selec6ActionPerformed(evt);
            }
        });
        
        ArrayList<Disk_02> diskList = Disk_02.getDiskList();
        Disk_02 disk = diskList.get(0);
        Object[][] data = new Object[diskList.size()][11];

        for (int i = 0; i < diskList.size(); i++) {
        	Disk_02 ds = diskList.get(i);
            data[i][0] = ds.getProdctid();
            data[i][1] = ds.getDiskid();
            data[i][2] = ds.getDiskdata();
            data[i][3] = ds.getPrice();
        }
        
        if (diskList.size() > 9) {
        	Disk_02 disk9 = diskList.get(9);
        jLabel4.setText(disk9.getDiskid());
        jLabel3.setText(disk9.getPrice());
        jLabel5.setText(disk9.getProdctid());
        jLabel8.setText(disk9.getDiskdata());
        }
        
        if (diskList.size() > 10) {
        	Disk_02 disk10 = diskList.get(10);
        jLabel10.setText(disk10.getDiskid());
        jLabel11.setText(disk10.getPrice());
        jLabel12.setText(disk10.getProdctid());
        jLabel13.setText(disk10.getDiskdata());
        }
        
        if (diskList.size() > 11) {
        	Disk_02 disk11 = diskList.get(11);
        jLabel14.setText(disk11.getDiskid());
        jLabel16.setText(disk11.getPrice());
        jLabel18.setText(disk11.getProdctid());
        jLabel19.setText(disk11.getDiskdata());
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl_Gpu5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_Name5)
                            .addComponent(Lbl_Info5)
                            .addComponent(Lbl_Exam5)
                            .addComponent(Lbl_Price5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl_Gpu4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_Name4)
                            .addComponent(Lbl_Price4)
                            .addComponent(Lbl_Exam4)
                            .addComponent(Lbl_Info4)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl_Gpu6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_Price6)
                            .addComponent(Lbl_Name6)
                            .addComponent(Lbl_Exam6)
                            .addComponent(Lbl_Info6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_Selec6)
                    .addComponent(Btn_Selec5)
                    .addComponent(Btn_Selec4))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_Previous, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl_Gpu4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_Gpu5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lbl_Name5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Lbl_Price5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Lbl_Info5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Lbl_Exam5)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Lbl_Gpu6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lbl_Info6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_Previous, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lbl_Name6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Lbl_Price6)
                                .addGap(26, 26, 26)
                                .addComponent(Lbl_Exam6))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl_Name4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn_Selec4)
                                .addGap(95, 95, 95)
                                .addComponent(Btn_Selec5)
                                .addGap(95, 95, 95)
                                .addComponent(Btn_Selec6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lbl_Price4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Lbl_Info4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Lbl_Exam4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_PreviousActionPerformed
        // TODO add your handling code here:
        Frame_Gpu pre = new Frame_Gpu();
        dispose();
        pre.setVisible(true);
    }//GEN-LAST:event_Button_PreviousActionPerformed

    private void Btn_Selec4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Selec4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Selec4ActionPerformed

    private void Btn_Selec5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Selec5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Selec5ActionPerformed

    private void Btn_Selec6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Selec6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Selec6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_GpuNext2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_GpuNext2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_GpuNext2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_GpuNext2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_GpuNext2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Selec4;
    private javax.swing.JButton Btn_Selec5;
    private javax.swing.JButton Btn_Selec6;
    private javax.swing.JButton Button_Previous;
    private javax.swing.JLabel Lbl_Exam4;
    private javax.swing.JLabel Lbl_Exam5;
    private javax.swing.JLabel Lbl_Exam6;
    private javax.swing.JLabel Lbl_Gpu4;
    private javax.swing.JLabel Lbl_Gpu5;
    private javax.swing.JLabel Lbl_Gpu6;
    private javax.swing.JLabel Lbl_Info4;
    private javax.swing.JLabel Lbl_Info5;
    private javax.swing.JLabel Lbl_Info6;
    private javax.swing.JLabel Lbl_Name4;
    private javax.swing.JLabel Lbl_Name5;
    private javax.swing.JLabel Lbl_Name6;
    private javax.swing.JLabel Lbl_Price4;
    private javax.swing.JLabel Lbl_Price5;
    private javax.swing.JLabel Lbl_Price6;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
